import { type INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { beforeAll, afterAll, beforeEach, afterEach, describe, expect, it } from 'vitest';
import request from 'supertest';
import { randomUUID, randomBytes } from 'node:crypto';
import { AppModule } from '../src/app.module.js';
import { PrismaService } from '../src/prisma.service.js';
import { PasswordHasher } from '../src/modules/users/password-hasher.js';
import { browserSecurity } from '../src/common/browser-security.js';
import { validationPipe } from '../src/common/http.js';
import { digest, encryptCredential } from '../src/modules/payments/payment-security.js';
describe('Sessões do navegador e links de inscrição',()=>{
  let app:INestApplication;let prisma:PrismaService;let id:string;let eventId:string;let registrationId:string;
  beforeAll(async()=>{const module=await Test.createTestingModule({imports:[AppModule]}).compile();app=module.createNestApplication();app.use(browserSecurity);app.useGlobalPipes(validationPipe());await app.init();prisma=app.get(PrismaService);});
  beforeEach(async()=>{id=randomUUID();eventId=randomUUID();registrationId=randomUUID();await prisma.user.create({data:{id,name:'Teste navegador',email:`${id}@ligahub.test`,role:'admin',passwordHash:await app.get(PasswordHasher).hash('senha-de-teste')}});});
  afterEach(async()=>{await prisma.registration.deleteMany({where:{id:registrationId}});await prisma.academicEvent.deleteMany({where:{id:eventId}});await prisma.auditLog.deleteMany({where:{actorId:id}});await prisma.browserSession.deleteMany({where:{userId:id}});await prisma.user.deleteMany({where:{id}});});
  afterAll(async()=>{await app?.close();});
  async function browser(){const agent=request.agent(app.getHttpServer());const csrf=await agent.get('/browser/csrf').expect(200);return {agent,csrf:csrf.body.token as string};}
  async function login(){const client=await browser();const response=await client.agent.post('/auth/login').set('x-browser-client','1').set('x-csrf-token',client.csrf).send({email:`${id}@ligahub.test`,password:'senha-de-teste'}).expect(200);return {...client,response};}
  it('emite cookies HttpOnly sem expor JWT e rejeita CSRF ausente',async()=>{const {agent,response}=await login();expect(response.body.accessToken).toBeUndefined();expect(response.headers['set-cookie'].join(';')).toContain('HttpOnly');await agent.get('/auth/me').expect(200);await agent.post('/auth/logout').set('x-browser-client','1').expect(403);});
  it('renova a sessão e revoga acesso e refresh ao detectar reutilização',async()=>{const {agent,csrf,response}=await login();const old=response.headers['set-cookie'].find((c:string)=>c.startsWith('lh_refresh=')).split(';')[0];const refresh=await agent.post('/auth/refresh').set('x-browser-client','1').set('x-csrf-token',csrf).expect(204);const csrfCookie=(await agent.get('/browser/csrf')).headers['set-cookie'][0].split(';')[0];await request(app.getHttpServer()).post('/auth/refresh').set('Cookie',`${old}; ${csrfCookie}`).set('x-browser-client','1').set('x-csrf-token',csrf).expect(401);await agent.get('/auth/me').expect(401);expect(refresh.headers['set-cookie'].join(';')).toContain('lh_refresh=');});
  it('impede renovar após 8h e invalida sessão ao suspender a conta',async()=>{const {agent,csrf}=await login();await prisma.browserSession.updateMany({where:{userId:id},data:{expiresAt:new Date(Date.now()-1000)}});await agent.post('/auth/refresh').set('x-browser-client','1').set('x-csrf-token',csrf).expect(401);const second=await login();await prisma.user.update({where:{id},data:{active:false}});await second.agent.get('/auth/me').expect(401);await second.agent.post('/auth/refresh').set('x-browser-client','1').set('x-csrf-token',second.csrf).expect(401);});
  it('troca link uma única vez por cookie restrito à inscrição e recusa link expirado',async()=>{await prisma.academicEvent.create({data:{id:eventId,title:'Evento',priceInCents:2500,capacity:2,ownerId:id}});const management=randomBytes(32).toString('base64url');await prisma.registration.create({data:{id:registrationId,eventId,name:'Ana',email:'ana@ligahub.test',answers:{},formSnapshot:[],priceInCents:2500,reservationExpiresAt:new Date(Date.now()+900_000),manageTokenHash:digest(management),manageTokenEncrypted:encryptCredential(management)}});const token=randomBytes(32).toString('base64url');await prisma.registrationAccessLink.create({data:{registrationId,tokenHash:digest(token),expiresAt:new Date(Date.now()+900_000)}});const {agent,csrf}=await browser();await agent.post(`/public/registrations/${registrationId}/access`).set('x-browser-client','1').set('x-csrf-token',csrf).send({token}).expect(204);await agent.get(`/public/registrations/${registrationId}`).expect(200);await agent.get(`/public/registrations/${randomUUID()}`).expect(401);await agent.post(`/public/registrations/${registrationId}/access`).set('x-browser-client','1').set('x-csrf-token',csrf).send({token}).expect(401);const expired=randomBytes(32).toString('base64url');await prisma.registrationAccessLink.create({data:{registrationId,tokenHash:digest(expired),expiresAt:new Date(Date.now()-1000)}});await agent.post(`/public/registrations/${registrationId}/access`).set('x-browser-client','1').set('x-csrf-token',csrf).send({token:expired}).expect(401);});
});
